import { Link } from 'react-router-dom';
import { ArrowRight, CalendarBlank, ChatCircleDots, CheckCircle, HouseLine, MagnifyingGlass, ShieldCheck, WarningCircle } from '@phosphor-icons/react';
import { ButtonLink } from '../components/UI';

function InfoHero({ eyebrow, title, body, image }) { return <div className="info-hero shell"><div><p className="overline">{eyebrow}</p><h1>{title}</h1><p>{body}</p></div><img src={image} alt="Student apartment interior" /></div>; }

export function HowItWorks() { return <><InfoHero eyebrow="A simpler way to sublease" title={<>A clear path from<br />space to stay.</>} body="One place to share a room, find a fit, and have the conversation that moves things forward." image="/images/room-olive.jpg" /><section className="section shell info-steps"><div><span>01</span><MagnifyingGlass size={29} /><h2>Find or share a room</h2><p>Browse by school, city, dates, price, and room type. If you are leaving town, create a listing with real photos and clear terms.</p></div><div><span>02</span><ChatCircleDots size={29} /><h2>Talk directly</h2><p>Ask about the space and the dates in a conversation attached to the listing. Keep the key details together.</p></div><div><span>03</span><ShieldCheck size={29} /><h2>Confirm the handoff</h2><p>Check your lease, verify identities, and get written approval from the landlord or property manager before exchanging money.</p></div></section><section className="info-banner shell"><div><p className="overline">Ready to start?</p><h2>Your next move is right here.</h2></div><div><ButtonLink to="/explore">Explore rooms <ArrowRight size={17} /></ButtonLink><ButtonLink to="/post" variant="outline">Post a room</ButtonLink></div></section></>; }

export function Pricing() { return <><InfoHero eyebrow="Simple pricing" title={<>One listing.<br />One clear price.</>} body="Create a draft for free. Pay only when you are ready to publish your room." image="/images/studio-sunlit.jpg" /><section className="pricing-layout shell"><div className="price-card"><p className="overline">For students sharing a room</p><div className="big-price">$25 <span>/ listing</span></div><p>One-time charge to publish a listing. You can edit it and update availability after publication.</p><ul><li><CheckCircle size={18} /> Create and preview a draft for free</li><li><CheckCircle size={18} /> Add up to five photos</li><li><CheckCircle size={18} /> Receive and reply to student inquiries</li></ul><ButtonLink to="/post">Create your listing <ArrowRight size={17} /></ButtonLink></div><div className="price-explainer"><h2>What about renters?</h2><p>Browsing, saving rooms, and messaging posters are free. Rent and deposits are arranged outside the app for now, after both parties confirm the lease and approval.</p><h2>Monthly rent payments</h2><p>In-app rent payments are a planned future feature, with a proposed $5 fee per monthly payment. They are not available in this version.</p><Link className="text-link" to="/safety">Read the safety guide <ArrowRight size={16} /></Link></div></section></>; }

export function Safety() { return <><InfoHero eyebrow="Stay thoughtful" title={<>Good matches<br />start with trust.</>} body="A school email helps focus this community, but every sublease still needs careful checks by the people involved." image="/images/room-blue.jpg" /><section className="section shell safety-grid"><div><ShieldCheck size={29} /><h2>Check the lease first</h2><p>Confirm that subleasing is allowed and ask for written approval from the landlord or property manager. A poster's approval status is self reported.</p></div><div><HouseLine size={29} /><h2>See the actual space</h2><p>Ask for a live tour or visit in person. Compare photos, address details, and lease documents before committing.</p></div><div><CalendarBlank size={29} /><h2>Put terms in writing</h2><p>Agree on exact dates, rent, utilities, deposit, keys, and who is responsible if plans change.</p></div><div><WarningCircle size={29} /><h2>Pause when pressured</h2><p>Be wary of rushed deposits, unusual payment requests, or anyone unwilling to verify their identity or lease rights. Report suspicious listings.</p></div></section><section className="info-banner shell"><div><p className="overline">Find your place</p><h2>Browse with a little more confidence.</h2></div><ButtonLink to="/explore">Explore rooms <ArrowRight size={17} /></ButtonLink></section></>; }
